common_params:
  learning_rate:
    type: float
    min: 1.0e-4
    max: 1.0e-2
    log: true
  weight_decay:
    type: float
    min: 1.0e-6
    max: 1.0e-2
    log: true
  batch_size:
    type: categorical
    choices: [32, 64, 128, 256]
  dropout:
    type: float
    min: 0.1
    max: 0.5

# 학습 관련 설정
patience: 10
max_epochs: 50