common_params:
  learning_rate:
    type: float
    min: 1.0e-4
    max: 1.0e-2
    log: true
  weight_decay:
    type: float
    min: 1.0e-6
    max: 1.0e-2
    log: true
  batch_size:
    type: categorical
    choices: [32, 64, 128, 256]
  dropout:
    type: float
    min: 0.1
    max: 0.5

model_params:
  d_model:
    type: categorical
    choices: [64, 128, 256, 512]
  e_layers:
    type: int
    min: 1
    max: 4

# 학습 관련 설정
patience: 15
max_epochs: 50